### ISSUE TITLE
Seq2seq解决多标签情感分析代码

### ISSUE THREAD

**Issue by yuerxin1997** [Decalogue/AI_Competition#2]
您好，请问这是用Seq2seq解决多标签情感分析的代码吗？我在coling2018 SGM那篇文章看到您的回复。

**Comment by Decalogue** [comment]
@yuerxin1997 您好！是的。是将所有20个标签连接的字符序列作为 target. 和季军思路是完全一样的。季军在很多细节都做了创新改进。

**Comment by Decalogue** [comment]
这个比赛栏目之后会整个修改，以分享更多的内容。

**Comment by yuerxin1997** [comment]
您好！感谢您回复，另外我想确认一下，您是第四名是吗？ 谢谢！🙏

**Comment by Decalogue** [comment]
我不是第四名,第四名是我朋友
